version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_DB=antchito
      - POSTGRES_USER=antchito
      - POSTGRES_PASSWORD=Password
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8080"